apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: argocd-flask-demo
  name: argocd-flask-demo
spec:
  containers:
  - image: scottwatson/argocd-flask-demo-repo:0.0.1
    name: argocd-flask-demo
    resources: {}
    ports:
    - containerPort: 8765
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}