apiVersion: v1
kind: Service
metadata:
  name: argocd-flask-demo
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: argocd-flask-demo
status:
  loadBalancer: {}
